(function(){
'use strict';
var state={provider:'deepseek',video:null,videoMeta:null,lastTask:'',lastAnalysis:null};
var AI={deepseek:'DeepSeek',kimi:'Kimi',gpt:'GPT',gemini:'Gemini'};
function $(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function setStatus(id,t,kind){var e=$(id);if(e){e.textContent=t;e.className='status-line '+(kind||'')}}
function aiSelect(id){return '<select id="'+id+'" class="ai-select">'+Object.keys(AI).map(k=>'<option value="'+k+'" '+(state.provider===k?'selected':'')+'>'+AI[k]+'</option>').join('')+'</select>'}
function providerButtons(taskId){return '<div class="ai-actions"><button class="btn primary" data-ai="deepseek" data-task="'+taskId+'">DeepSeek</button><button class="btn primary" data-ai="kimi" data-task="'+taskId+'">Kimi</button><button class="btn primary" data-ai="gpt" data-task="'+taskId+'">GPT</button><button class="btn primary" data-ai="gemini" data-task="'+taskId+'">Gemini</button></div>'}
function panel(title,body){return '<div class="panel"><h3>'+title+'</h3>'+body+'</div>'}
function mount(){
 var main=document.getElementById('main');
 main.innerHTML=''+
 '<section class="view active" id="view-home"><div class="view-head"><h2>AI制片台</h2><p>把视频、数据和一句人话交给 AI；AI负责导演判断、增长诊断和方法提炼。</p></div><div id="home-body"></div></section>'+
 '<section class="view" id="view-director"><div class="view-head"><h2>AI导演</h2><p>不让你选景别、运镜和动作。AI先理解你真正想表达的情绪，再决定怎么拍。</p></div><div id="director-body"></div></section>'+
 '<section class="view" id="view-video"><div class="view-head"><h2>视频分析</h2><p>直接上传视频，高密度抽帧；分析镜头、人物、情绪、环境与真正值得复制的影视逻辑。</p></div><div id="video-body"></div></section>'+
 '<section class="view" id="view-hot"><div class="view-head"><h2>爆款拆解</h2><p>上传一个你认为值得研究的作品，再填它的真实数据，让 AI 判断它为什么获得播放和互动。</p></div><div id="hot-body"></div></section>'+
 '<section class="view" id="view-growth"><div class="view-head"><h2>我的视频诊断</h2><p>输入你自己的视频和传播数据，AI判断为什么结果好或差，优先告诉你最该改哪一处。</p></div><div id="growth-body"></div></section>'+
 '<section class="view" id="view-report"><div class="view-head"><h2>制片报告</h2><p>把分析结果自动整理成汇报结构；不再让你手工填 PPT。</p></div><div id="report-body"></div></section>'+
 '<section class="view" id="view-script"><iframe src="modules/script-tagging/index.html" title="剧本标注工作台" style="width:100%;height:calc(100vh - 110px);border:1px solid var(--line);border-radius:10px;background:#fff"></iframe></section>';
 document.getElementById('module-nav').innerHTML=[['home','首页'],['script','剧本标注'],['director','AI导演'],['video','视频分析'],['hot','爆款拆解'],['growth','我的诊断'],['report','报告']].map((x,i)=>'<button class="nav-item '+(i===0?'active':'')+'" data-view="'+x[0]+'"><span class="n-icon">'+(['⌂','▤','✦','▶','↗','▥','▤'][i])+'</span><span class="n-title">'+x[1]+'</span></button>').join('');
 document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>activate(b.dataset.view));
 renderHome();renderDirector();renderVideo();renderHot();renderGrowth();renderReport();
}
function activate(v){document.querySelectorAll('.view').forEach(e=>e.classList.toggle('active',e.id==='view-'+v));document.querySelectorAll('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.view===v));var titles={home:'首页',script:'剧本标注',director:'AI导演',video:'视频分析',hot:'爆款拆解',growth:'我的诊断',report:'制片报告'};var t=$('topbar-title');if(t)t.textContent=titles[v]||'AI制片台';}
function taskCard(taskId){return '<div class="output-block"><div class="out-head"><h4>AI任务已准备</h4><span>'+aiSelect('provider-'+taskId)+'</span></div><p class="hint">选择 AI 后直接打开网页版并自动填入。无需 API Key；默认停在发送前，方便你最后检查。</p><details><summary>查看完整任务</summary><pre id="task-'+taskId+'">'+esc(state[taskId]||'')+'</pre></details>'+providerButtons(taskId)+'</div>'}
function bindAI(){document.querySelectorAll('.ai-select').forEach(s=>s.onchange=()=>state.provider=s.value);document.querySelectorAll('[data-ai][data-task]').forEach(b=>b.onclick=async()=>{var task=state[b.dataset.task];if(!task)return;var r=await Handoff.sendToChat(b.dataset.ai,task);alert(r.message);});}
function renderHome(){
 $('home-body').innerHTML=panel('今天要做什么？','<div class="home-grid"><button class="home-card" data-go="script"><b>剧本 → AI导演 → LibTV</b><span>先写剧本，再让 AI 自动补齐景别、构图、运镜、动作和最终提示词</span></button><button class="home-card" data-go="director"><b>一句人话 → AI导演</b><span>不让你逐项选镜头参数，AI直接判断怎么拍</span></button><button class="home-card" data-go="video"><b>分析一个视频</b><span>上传视频 → 找出镜头、情绪、节奏和可复制方法</span></button><button class="home-card" data-go="hot"><b>拆一个爆款</b><span>视频 + 播放互动数据 → 判断为什么爆</span></button></div>')+panel('AI大脑','<p class="hint">所有核心功能都可以交给同一套 AI：DeepSeek、Kimi、GPT、Gemini。这里不要求 API Key。</p><div class="ai-row">'+aiSelect('global-ai')+'<span class="status-line ok">当前默认：'+AI[state.provider]+'</span></div>');document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>activate(b.dataset.go));bindAI();}
function renderDirector(){
 $('director-body').innerHTML=panel('① 说人话','<textarea id="dir-input" rows="7" placeholder="例如：两个人在街上聊天，表面很轻松，但其中一个人知道这是最后一次见面。我想要克制、不说破的难过。"></textarea>')+panel('② AI导演任务','<p class="hint">AI自行判断：核心情绪 → 人物关系 → 情绪转折 → 成熟影视表达 → 人物微动作 → 环境生命力。你不需要选择任何镜头参数。</p><div class="btn-row"><button class="btn primary" id="dir-build">生成导演任务</button><span id="dir-status" class="status-line"></span></div><div id="dir-output"></div>');$('dir-build').onclick=()=>{var x=$('dir-input').value.trim();if(!x){setStatus('dir-status','先说一下你想拍什么','err');return;}state.dirTask=`你是资深影视导演和AI视频导演。请理解下面这段大白话，不要反问我，也不要让我选择场景、景别、镜头或运镜。先判断最重要的核心情绪、潜在情绪、人物关系和情绪转折，再使用成熟电影/电视剧验证过的通用影视逻辑完成拍摄设计。\n\n【用户描述】\n${x}\n\n【执行原则】\n1. 用户明确指定的情绪最高优先级；未指定则自行判断。\n2. 场景只是承载情绪的手段，你自己选择。\n3. 同框人物必须自然生活：说话者之外的人要有符合情境的视线、呼吸、手部、身体重心、回应或继续手头事情等微动作；动物同理。\n4. 环境保持生命力，只补1—3个合理背景动态，不抢主角。\n5. 不堆“电影感/大片感/高级感/8K”等空词；用真正影响生成的具体信息表达。\n6. 沿用成熟影视叙事和镜头逻辑，不为了炫技发明复杂运镜。\n\n【输出】\nA 核心情绪：一句话\nB 最终中文视频Prompt：短、准、可直接给AI视频模型\nC 为什么这样拍：一句话\nD 一个最关键的导演提醒：只说最影响成片的一点。`; $('dir-output').innerHTML=taskCard('dirTask');bindAI();setStatus('dir-status','已生成','ok');};}
function videoPanel(prefix,title){return panel(title,'<div class="field"><label>视频文件</label><input type="file" id="'+prefix+'-file" accept="video/*"><div id="'+prefix+'-meta" class="hint">支持 MP4 / MOV / WebM 等浏览器可读取格式</div><video id="'+prefix+'-preview" class="video-preview" controls muted style="display:none"></video></div><div class="grid-4"><div class="field"><label>抽帧密度</label><select id="'+prefix+'-density"><option value="0.6">智能 · 约0.6帧/秒</option><option value="0.9" selected>标准 · 约0.9帧/秒</option><option value="1.5">高密度 · 约1.5帧/秒</option><option value="manual">手动 96 帧</option></select></div><div class="field"><label>播放量</label><input id="'+prefix+'-views" type="number" placeholder="可选"></div><div class="field"><label>点赞</label><input id="'+prefix+'-likes" type="number" placeholder="可选"></div><div class="field"><label>评论</label><input id="'+prefix+'-comments" type="number" placeholder="可选"></div></div>');}
function attachVideo(prefix,cb){$(prefix+'-file').onchange=function(){var f=this.files&&this.files[0];if(!f)return;var u=URL.createObjectURL(f),v=$(prefix+'-preview');v.src=u;v.style.display='block';v.onloadedmetadata=function(){var d=v.duration||0;$(prefix+'-meta').textContent=f.name+' · '+d.toFixed(1)+'秒 · 建议抽帧 '+Math.min(300,Math.max(24,Math.ceil(d*0.9)))+' 帧';cb(f,v,d);};};}
function renderVideo(){
 $('video-body').innerHTML=videoPanel('va','上传视频')+panel('AI视频理解','<p class="hint">本地只负责读取视频时长、抽帧和生成分析任务；真正的影视判断交给你选择的 AI。</p><div class="btn-row"><button class="btn primary" id="va-build">生成视频分析任务</button><span id="va-status" class="status-line"></span></div><div id="va-output"></div>');
 attachVideo('va',function(f,v,d){state.videoMeta={name:f.name,duration:d};});
 $('va-build').onclick=async function(){if(!state.videoMeta){setStatus('va-status','先上传视频','err');return;}var den=$('va-density').value;var fps=den==='manual'?96:Math.min(300,Math.max(24,Math.ceil(state.videoMeta.duration*Number(den))));state.vaTask=`你是资深短视频导演、剪辑师和内容增长分析师。请分析我上传的视频（${state.videoMeta.name}，${state.videoMeta.duration.toFixed(1)}秒；制片台已按约${fps}帧进行高密度关键帧采样）。不要只描述画面，要解释“为什么有效/为什么无效”。\n\n请依次判断：\n1. 核心主题与核心情绪，以及情绪如何变化。\n2. 前3秒、前10秒和关键转折点为什么能/不能留住人。\n3. 镜头逻辑：景别、构图、视线关系、机位和运动方式只在真正有叙事作用时说明。\n4. 人物：位置、进入/退出、互动、主体动作、自然微动作、面部状态。\n5. 环境：前中后景、行人/车辆/动物/生活活动，是否形成真实世界。\n6. 节奏：信息释放、情绪升级、停顿、反转、结尾落点。\n7. 找出3—5个最值得复制的成熟电影/电视剧式方法，说明它服务什么目的。不要凭空发明炫技镜头。\n8. 给出一段简洁的“可迁移方法”，不要照抄故事。\n9. 最后给出：最值得保留的一点、最值得改的一点。\n\n如果关键帧无法支持某个判断，明确说“不足以判断”，不要编造。`; $('va-output').innerHTML=taskCard('vaTask');bindAI();setStatus('va-status','任务已生成。下一步把视频/关键帧交给网页AI分析。','ok');};}
function metrics(prefix){return '<div class="grid-4"><div class="field"><label>播放量</label><input id="'+prefix+'-views" type="number" placeholder="例如 320000"></div><div class="field"><label>点赞</label><input id="'+prefix+'-likes" type="number" placeholder="例如 28000"></div><div class="field"><label>评论</label><input id="'+prefix+'-comments" type="number" placeholder="例如 1200"></div><div class="field"><label>转发</label><input id="'+prefix+'-shares" type="number" placeholder="例如 5600"></div></div><div class="grid-4"><div class="field"><label>收藏</label><input id="'+prefix+'-saves" type="number" placeholder="可选"></div><div class="field"><label>完播率 %</label><input id="'+prefix+'-completion" type="number" step="0.1" placeholder="可选"></div><div class="field"><label>平均观看时长 秒</label><input id="'+prefix+'-avg" type="number" step="0.1" placeholder="可选"></div><div class="field"><label>粉丝量</label><input id="'+prefix+'-followers" type="number" placeholder="可选"></div></div>'}
function val(id){var n=Number($(id).value);return isFinite(n)&&n>0?n:null}
function renderHot(){
 $('hot-body').innerHTML=videoPanel('hot','① 爆款视频')+panel('② 真实传播数据',metrics('hot'))+panel('③ AI爆款判断','<textarea id="hot-note" rows="3" placeholder="可选：你为什么觉得它值得研究？"></textarea><div class="btn-row"><button class="btn primary" id="hot-build">生成爆款拆解任务</button><span id="hot-status" class="status-line"></span></div><div id="hot-output"></div>');
 attachVideo('hot',function(f,v,d){state.hotMeta={name:f.name,duration:d};});
 $('hot-build').onclick=function(){if(!state.hotMeta){setStatus('hot-status','先上传爆款视频','err');return;}var m=['播放量','点赞','评论','转发','收藏','完播率','平均观看时长','粉丝量'].map((x,i)=>x+': '+[val('hot-views'),val('hot-likes'),val('hot-comments'),val('hot-shares'),val('hot-saves'),val('hot-completion'),val('hot-avg'),val('hot-followers')][i]).join('；');state.hotTask=`你是一名短视频增长导演。请基于上传的爆款视频与真实传播数据做“为什么爆”的因果拆解。不要只给指标解释，也不要把相关性当因果。\n\n【视频】${state.hotMeta.name}，${state.hotMeta.duration.toFixed(1)}秒\n【数据】${m}\n【补充】${$('hot-note').value.trim()||'无'}\n\n请输出：\nA 爆款核心机制：最多3条，按重要性排序。\nB 前3秒：具体说明它给了观众什么继续看的理由。\nC 信息/情绪/冲突/反转：标出关键节点和作用。\nD 互动：点赞、评论、收藏、转发分别可能被什么内容触发；没有足够证据就标注推测。\nE 可复制方法：只提炼结构和方法，不复制故事、台词或表面包装。\nF 如果把这个视频换成普通账号来做，最容易失败的地方是什么。\nG 给我的下一条视频一个最值得执行的改动。`; $('hot-output').innerHTML=taskCard('hotTask');bindAI();setStatus('hot-status','任务已生成','ok');};}
function renderGrowth(){
 $('growth-body').innerHTML=videoPanel('my','① 我的原视频')+panel('② 我的真实传播数据',metrics('my')+'<div class="grid-3"><div class="field"><label>视频时长 秒</label><input id="my-duration" type="number" placeholder="例如 232"></div><div class="field"><label>目标播放</label><input id="my-target" type="number" placeholder="可选"></div><div class="field"><label>内容/人群补充</label><input id="my-audience" type="text" placeholder="例如 20–40岁故事内容"></div></div>')+panel('③ AI增长诊断','<p class="hint">你知道多少填多少。AI会区分“内容质量问题”和“传播效率问题”，优先找最值得改的一处。</p><div class="btn-row"><button class="btn primary" id="my-build">生成我的诊断任务</button><span id="my-status" class="status-line"></span></div><div id="my-output"></div>');
 attachVideo('my',function(f,v,d){state.myMeta={name:f.name,duration:d};$('my-duration').value=Math.round(d);});
 $('my-build').onclick=function(){if(!state.myMeta){setStatus('my-status','先上传自己的视频','err');return;}var vals={views:val('my-views'),likes:val('my-likes'),comments:val('my-comments'),shares:val('my-shares'),saves:val('my-saves'),completion:val('my-completion'),avg:val('my-avg'),followers:val('my-followers'),duration:val('my-duration'),target:val('my-target')};state.myTask=`你是一名短视频内容导演 + 增长分析师。请分析我上传的“自己的视频”，并结合真实传播数据判断为什么结果好或差。\n\n【视频】${state.myMeta.name}，${vals.duration||state.myMeta.duration.toFixed(1)}秒\n【数据】播放 ${vals.views}；点赞 ${vals.likes}；评论 ${vals.comments}；转发 ${vals.shares}；收藏 ${vals.saves}；完播率 ${vals.completion}%；平均观看 ${vals.avg}秒；发布时粉丝 ${vals.followers}；目标播放 ${vals.target}\n【补充】${$('my-audience').value.trim()||'无'}\n\n请严格按以下顺序：\n1. 先给结论：这条视频最大的问题/最大优势是什么，只说一个。\n2. 内容质量 vs 传播效率：分别判断，不要混为一谈。\n3. 前3秒、前10秒、第一次情绪/信息转折、结尾分别判断。\n4. 数据之间的关系：播放、点赞、评论、转发、收藏、完播、平均观看能支持什么判断；无法支持的不要猜。\n5. 找出用户最可能流失的位置，并说明为什么。\n6. 给出“如果只允许改3处”的修改方案，必须具体到内容/镜头/结构。\n7. 给出下一条视频可以直接复制的一个方法。\n8. 最后用一句话告诉创作者：不是哪里不好，而是哪里没有被用户及时看到。\n\n不要用“加强共鸣、提高节奏、电影感更强”这种空话。`; $('my-output').innerHTML=taskCard('myTask');bindAI();setStatus('my-status','诊断任务已生成','ok');};}
function renderReport(){
 $('report-body').innerHTML=panel('自动汇报','<p class="hint">把最近一次 AI 分析结果或你从 AI 网页复制回来的分析粘贴进来。制片台会自动整理成汇报结构，不需要手工写每一页。</p><textarea id="report-source" rows="10" placeholder="粘贴 DeepSeek / Kimi / GPT / Gemini 的分析结果……"></textarea><div class="btn-row"><button class="btn primary" id="report-build">生成PPT任务</button><button class="btn" id="report-local">用现有内容生成PPT</button><span id="report-status" class="status-line"></span></div><div id="report-output"></div>');
 $('report-build').onclick=function(){var x=$('report-source').value.trim();if(!x){setStatus('report-status','先粘贴一次AI分析结果','err');return;}state.reportTask=`请把下面这份视频/增长分析整理成专业、克制、可汇报的10页PPT内容。不要增加未经分析支持的事实。每页只保留最有价值的信息。\nP1 项目概览\nP2 为什么这个视频有效/无效\nP3 前3秒钩子\nP4 内容结构与信息释放\nP5 人物与镜头设计\nP6 情绪曲线\nP7 增长节点与数据关系\nP8 可复制的方法\nP9 对下一条视频的具体启发\nP10 最终结论\n每页输出：标题 + 1句结论 + 3条要点。\n\n【原始AI分析】\n${x}`;$('report-output').innerHTML=taskCard('reportTask');bindAI();setStatus('report-status','PPT内容任务已生成','ok');};
 $('report-local').onclick=function(){var x=$('report-source').value.trim();if(!x){setStatus('report-status','先粘贴分析结果','err');return;}var ppt=new PptxGenJS();ppt.layout='LAYOUT_WIDE';var lines=x.split(/\n+/).filter(Boolean);for(var i=0;i<10;i++){var s=ppt.addSlide();s.addText((i+1)+'. '+(lines[i]||'分析结论'),{x:.7,y:.6,w:12,h:.5,fontSize:24,bold:true});s.addText(lines.slice(i*3,i*3+3).join('\n')||x.slice(0,500),{x:.9,y:1.5,w:11.5,h:4.8,fontSize:15,breakLine:false,fit:'shrink'});}ppt.writeFile({fileName:'AI制片台-分析汇报.pptx'}).then(()=>setStatus('report-status','PPT已生成','ok')).catch(e=>setStatus('report-status','生成失败：'+e.message,'err'));};}
mount();
})();
